# Generated by Django 3.1.8 on 2021-06-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replyToId',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
